
server.port=8585
server.servlet.context-path=/workintech

management.info.env.enabled=true
management.endpoints.web.exposure.include=info,health,mappings

info.app.name=S17D2 Application
info.app.description=Developer Management System
info.app.version=0.0.1-SNAPSHOT